import { useMemo } from 'react';
import cn from 'classnames';
import useTranslation from 'next-translate/useTranslation';

import Avatar from 'components/avatar';
import Button from 'components/button';

import { SocialInterface, OrgJSON } from 'lib/model';
import Link from 'lib/intl/link';
import Utils from 'lib/utils';

import styles from './home.module.scss';

export interface HomeProps {
  org?: OrgJSON;
}

export default function Home({ org }: HomeProps): JSX.Element {
  const { t, lang: locale } = useTranslation();
  const autogeneratedAboutString = useMemo(() => {
    const as = org ? org.aspects : ['tutoring', 'mentoring'];
    let person = '';
    let people = '';
    if (as.includes('tutoring')) {
      person += 'tutor';
      people += 'tutors';
    }
    if (as.includes('mentoring')) {
      person += ' or mentor';
      people += ' and mentors';
    }
    const name = org ? org.name : 'This organization';
    return t('home:about', { name, person, people, aspects: Utils.join(as) });
  }, [org, t]);

  return (
    <div className={cn({ [styles.loading]: !org })}>
      {(!org || org.home[locale].photo) && (
        <div className={styles.background}>
          <img
            src={org && org.home[locale].photo}
            alt={`Background of ${org ? org.name : 'Organization'}`}
          />
        </div>
      )}
      <div className={styles.content}>
        <div className={styles.left}>
          <div className={styles.wrapper}>
            <a
              className={styles.img}
              href={org && org.photo}
              target='_blank'
              rel='noreferrer'
              tabIndex={-1}
            >
              <Avatar loading={!org} src={org && org.photo} />
            </a>
            <div>
              <h1 data-cy='name' className={styles.name}>
                {org && org.name}
              </h1>
              {(!org || !!org.socials.length) && (
                <div className={styles.socials}>
                  {(org ? org.socials : []).map((social: SocialInterface) => (
                    <a
                      key={social.type}
                      target='_blank'
                      rel='noreferrer'
                      href={social.url}
                      className={`${styles.socialLink} ${styles[social.type]}`}
                    >
                      {social.type}
                    </a>
                  ))}
                </div>
              )}
            </div>
          </div>
          <h2 className={styles.header}>{org && t('common:about')}</h2>
          <p className={styles.body}>{org && org.bio}</p>
          <p className={styles.body}>{org && autogeneratedAboutString}</p>
          <h2 className={styles.header}>{org && org.home[locale].header}</h2>
          <p className={styles.body}>{org && org.home[locale].body}</p>
        </div>
        <div className={styles.right}>
          <div className={styles.actions}>
            {(org ? org.aspects : ['tutoring', 'mentoring']).map((aspect) => (
              <div key={aspect} className={styles.card}>
                <Link
                  href='/[org]/search/[[...slug]]'
                  as={`/${org ? org.id : 'default'}/search?aspect=${aspect}`}
                >
                  <a>
                    <Button
                      className={styles.btn}
                      label={t(`home:search-${aspect}`)}
                      raised
                      arrow
                    />
                  </a>
                </Link>
                <Link
                  href='/[org]/signup'
                  as={`/${org ? org.id : 'default'}/signup?aspect=${aspect}`}
                >
                  <a>
                    <Button
                      className={styles.btn}
                      label={t(`home:signup-${aspect}`)}
                      outlined
                      arrow
                    />
                  </a>
                </Link>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
